spring:
  profiles:
    #激活开发环境
    active: dev
  messages:
    basename: i18n/Messages,i18n/Pages
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录

  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
logging:
  config: classpath:log4j2.yml
springfox:
  documentation:
    enabled: true
swagger:
  base-package: com.dr.code.diff.controller
  authorization:
    type: None
#knife4j:
#  enable: true
#  openapi:
#    title: Knife4j官方文档
#    version: v4.0
#    license: Apache 2.0
#    group:
#      test1:
#        group-name: 分组名称
#        api-rule: package
#        api-rule-resources:
#          - com.dr.code.diff.controller
#  globalOperationParameters:
#    - name: Authorization
#      description: 验证
#      type: string
#      required: false
#      parameterType: header

#shiro:
#  loginUrl: /view/sys/user/login
#  successUrl: /view/sys/index
#  unauthorizedUrl: /view/sys/unauthorized
#  sessionManager:
#    sessionIdUrlRewritingEnabled: false
git:
  userName: ray1
  password: 12345456
  local:
    base:
      dir: /Users/rayduan/app/git-test
  ssh:
    priKey: C:\Users\mylocl/.ssh/id_rsa.
svn:
  userName: admin
  password: 123456
  local:
    base:
      dir: D:\svn-test
maven:
  home: E:/Program Files/apache-maven-3.6.3
#代码的根目录，非标准maven项目需要自定义
root:
  code:
    path: src/main/java/
jacoco:
  root:
    path: H:/jacoco/root/
custom:
  link:
    start:
      classNameList:
        - com/dr/common/utils/mapper/OrikaMapperUtils
      methodSignList:
        - com/dr/code/diff/service/CodeDiffService#getDiffCode#DiffMethodParams
        - com/dr/code/diff/analyze/bean/ClassInfo#getSuperClassName#
    type: 2 #此处表示调用链排除jdk本身方法
  dubbo:
    xml:
      path: ""
server:
  port: 8085
  servlet:
    session:
      timeout: 3600


